server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5s
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        compression.type: lz4

jwt:
  private-key-path: ${PRIVATE_KEY_PATH:classpath:keys/private.pem}
  public-key-path: ${PUBLIC_KEY_PATH:classpath:keys/public.pem}
  access-token:
    expiration: 86400000
  refresh-token:
    expiration: 604800000
auth:
  jwt:
    issuer: novaplay-auth
    audience: novaplay
    kid: v1

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    vn:
      iotstar:
        authservice: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
