spring:
  config:
    import: optional:configserver:http://localhost:8888/
    activate:
      on-profile: dev

auth:
  jwt:
    issuer: novaplay-auth
    audience: novaplay
    kid: v1
    expiration: 900000
    refresh-token:
      expiration: 2592000000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: auth-service
