--liquibase formatted sql

-- Baseline: chụp lại schema đang chạy, trích từ k8s/infra/postgres-initdb.sql (bản pg_dump).
--
-- Tên FK trong bản dump là hash do Hibernate sinh (fk2dylsfo39lgjyqml2tbe0b0ss...) từ thời
-- ddl-auto=update. Ở đây đặt lại tên đọc được: Hibernate `validate` chỉ kiểm tra bảng/cột/kiểu,
-- KHÔNG kiểm tra tên constraint, nên đổi tên là an toàn và giúp đọc lỗi vi phạm FK dễ hơn nhiều.
--
-- DB dev hiện có được tạo từ bản dump chứ không phải từ file này (dev tắt Liquibase). Nếu cần
-- bật Liquibase trên một DB đã có sẵn schema, chạy `liquibase changelogSync` để đánh dấu
-- changeset là đã áp dụng thay vì để nó cố tạo lại bảng.

--changeset novaplay:001-users
CREATE TABLE users (
    user_id           uuid NOT NULL,
    created_at        timestamp(6) with time zone,
    created_by        varchar(255),
    updated_at        timestamp(6) with time zone,
    updated_by        varchar(255),
    email             varchar(255),
    is_active         boolean,
    is_email_verified boolean NOT NULL,
    last_login_at     timestamp(6) without time zone,
    password          varchar(255),
    username          varchar(255),
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT uk_user_email UNIQUE (email),
    CONSTRAINT uk_user_username UNIQUE (username)
);
CREATE INDEX idx_user_is_active ON users USING btree (is_active);
--rollback DROP TABLE users;

--changeset novaplay:002-roles
CREATE TABLE roles (
    role_id          uuid NOT NULL,
    created_at       timestamp(6) with time zone,
    created_by       varchar(255),
    updated_at       timestamp(6) with time zone,
    updated_by       varchar(255),
    role_description varchar(255),
    role_name        varchar(255),
    CONSTRAINT roles_pkey PRIMARY KEY (role_id),
    CONSTRAINT uk_role_role_name UNIQUE (role_name),
    CONSTRAINT roles_role_name_check CHECK (role_name::text = ANY (ARRAY['USER'::varchar, 'ADMIN'::varchar]::text[]))
);
--rollback DROP TABLE roles;

--changeset novaplay:003-permissions
-- permission_id là IDENTITY (không phải sequence rời) — giữ đúng như schema đang chạy để
-- Hibernate validate không kêu lệch kiểu.
CREATE TABLE permissions (
    permission_id          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             timestamp(6) with time zone,
    created_by             varchar(255),
    updated_at             timestamp(6) with time zone,
    updated_by             varchar(255),
    permission_description varchar(255),
    permission_name        varchar(100) NOT NULL,
    CONSTRAINT permissions_pkey PRIMARY KEY (permission_id),
    CONSTRAINT uk_permission_name UNIQUE (permission_name)
);
--rollback DROP TABLE permissions;

--changeset novaplay:004-tokens
CREATE TABLE tokens (
    token_id   uuid NOT NULL,
    created_at timestamp(6) with time zone,
    created_by varchar(255),
    updated_at timestamp(6) with time zone,
    updated_by varchar(255),
    expired_at timestamp(6) with time zone,
    is_revoked boolean,
    token      varchar(700),
    token_type varchar(255),
    user_id    uuid NOT NULL,
    CONSTRAINT tokens_pkey PRIMARY KEY (token_id),
    CONSTRAINT uk_token_value UNIQUE (token),
    CONSTRAINT tokens_token_type_check CHECK (token_type::text = ANY (ARRAY['ACCESS_TOKEN'::varchar, 'REFRESH_TOKEN'::varchar]::text[])),
    CONSTRAINT fk_tokens_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);
CREATE INDEX idx_token_user_id ON tokens USING btree (user_id);
CREATE INDEX idx_token_is_revoked ON tokens USING btree (is_revoked);
-- Job dọn token hết hạn quét theo expired_at (TokenServiceImpl#cleanupExpiredTokens). Không có
-- index này thì mỗi lượt chạy là một seq scan toàn bảng.
CREATE INDEX idx_token_expired_at ON tokens USING btree (expired_at);
--rollback DROP TABLE tokens;

--changeset novaplay:005-user-roles
CREATE TABLE user_roles (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (role_id)
);
--rollback DROP TABLE user_roles;

--changeset novaplay:006-role-permissions
CREATE TABLE role_permissions (
    role_id       uuid NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles (role_id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (permission_id)
);
--rollback DROP TABLE role_permissions;

--changeset novaplay:007-outbox-events
-- Bảng outbox của Transactional Outbox pattern. payload là jsonb; status/next_attempt_at điều
-- khiển việc thử lại. idx_outbox_due là PARTIAL index (chỉ row PENDING) — đây đúng là câu mà
-- OutboxDao#claimBatch quét kèm FOR UPDATE SKIP LOCKED, giữ nguyên mệnh đề WHERE nếu không
-- index sẽ không được dùng.
CREATE TABLE outbox_events (
    id              uuid NOT NULL,
    topic           varchar(255) NOT NULL,
    event_key       varchar(255),
    payload         jsonb NOT NULL,
    status          varchar(20) DEFAULT 'PENDING' NOT NULL,
    attempts        integer DEFAULT 0 NOT NULL,
    created_at      timestamp with time zone DEFAULT now() NOT NULL,
    next_attempt_at timestamp with time zone DEFAULT now() NOT NULL,
    error_message   varchar(2000),
    CONSTRAINT outbox_events_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_outbox_due ON outbox_events USING btree (next_attempt_at) WHERE status = 'PENDING';
--rollback DROP TABLE outbox_events;
