server:
  port: 8888
spring:
  profiles:
    active: default
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/81quanghuy/cloud_config_NovaPlay.git
          basedir: /opt/cloud-config-repo-novaPlay

          # --- THAY ĐỔI ĐỂ GỠ LỖI ---
          # Thêm dòng này để yêu cầu JGit bỏ qua việc xác thực chứng chỉ SSL.
          # Đây là bước để kiểm tra xem vấn đề có phải do kết nối bảo mật hay không.
          skip-ssl-validation: true

          # Vẫn giữ lại cài đặt này, không ảnh hưởng gì
          preferred-git-implementation: NATIVE

          # Sử dụng lại biến môi trường
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}

debug: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
