server:
  port: 8888
spring:
  profiles:
    active: default
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/81quanghuy/cloud_config_NovaPlay.git
          basedir: /opt/cloud-config-repo-novaPlay
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  kafka:
    bootstrap-servers: localhost:9092

debug: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"